name: SSC Quiz Test

on:
  workflow_dispatch:

jobs:
  send-quiz:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send SSC Quiz
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.SSC_CHAT_ID }}
          FILE_NAME: SSC_sample_10_questions.csv
        run: python bot.py
